server:
  port: 8080
  servlet:
    context-path: "/"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        output-out-0:
          destination: destGT
      default-binder: rabbit

  redis:
    database: 0
    host: localhost
    port: 16379
    password: mypass
    timeout: 60000

logging:
  level:
    root: INFO