version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/home/grzegorz/dev/rabbitmq/data
      - ~/.docker-conf/rabbitmq/log/:/home/grzegorz/dev/rabbitmq/log

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local