server:
  port: 8080
  servlet:
    context-path: "/"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      source: output
      bindings:
        output-out-0:
          destination: destGT
      default-binder: rabbit

logging:
  level:
    root: INFO