server:
  port: 8082
  servlet:
    context-path: "/"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    function:
      definition: status;result
    stream:
      bindings:
        status-in-0:
          destination: status
      default-binder: rabbit

  redis:
    database: 0
    host: localhost
    port: 16379
    password: mypass
    timeout: 60000

logging:
  level:
    root: INFO